# **9주차 과제**

- Colab 환경에서는 마크다운 셀의 보이지 않을 수 있으니, VS Code 등의 로컬환경을 사용하시거나 참고이미지 폴더의 파일들을을 참고하시길 바랍니다.

- 해당 과제는 VS Code, MySQL Workbench 환경에서 제작되었습니다.

- 출력 형태를 보며 display를 활용한 출력, print를 활용한 출력을 적절하게 사용해주시길 바랍니다.  
※ 이를 준수하지 않을 시에 오답의 요소가 될 수 있습니다.

---
## **Q1. Selenium을 실행하여 티스토리 메인 홈페이지로 이동**

`<img src="./9th_Weeks_images/Q1_Image_1.png" alt="1" style="width:60%; height:auto;">

- 상단에 첨부된 이미지 화면은 크롤링을 수행하는 시점마다 다르게 표현됩니다.

- 주소는 tstory url : https://www.tistory.com 을 사용해주세요

In [ ]:
# 코드 작성

''' 정답 코드를 작성해주세요 '''

---
## Q2. BeautifulSoup을 통해 html 정보 가져오고, 인기글 제목 출력
- 아래는 예시 이미지이며, 크롤링 수행시간마다 다르게 표현될 수 있습니다.
- 예시 이미지 기준으로 1, 2, 3, 4, 5 우측에 있는 글 제목을 출력하면 됩니다.
- 크롤링은 실시간으로 변하는 데이터이므로, 채점 시에 직접 실행해보고 결과 데이터를 확인하겠습니다.

*이탤릭체 텍스트*<img src="./9th_Weeks_images/Q1_Image_1.png" alt="1" style="width:60%; height:auto;">

- tag와 class 정보 확인해주세요
- find_all을 통해 정보 가져옵니다.

In [ ]:
''' 정답 코드를 작성해주세요 '''

(경기/고양시) 사유리 씨의 옛날보리밥과 코다리구이 ‘서삼능보리밥’
오늘 광명 이케아 가시는 분들 많으시죠? 미리 봐두시면 식당 이용하실 때 좋아요!
쿠팡봉지에 보이는 '구멍' 용도를 아시나요? 나만 모르면 손해입니다~
[내돈내산] 전참시 이연희 빵집 욥 위치,  '치즈 만주' 가격, 직접 사 본 후기
병원에서 보낸 5시간, 그리고 고깃집

**문제를 푸는 과정에서는 아래와 같이 구글링을 통해, 기능 검색을 해보시길 권장드립니다.**

<img src="./9th_Weeks_images/기능탐색.jpg" alt="1" style="width:80%; height:auto;">

---
## Q3. 메타코드 정보 검색, 데이터프레임으로 정보 저장

`<img src="./9th_Weeks_images/Q3_Image_1.png" alt="1" style="width:60%; height:auto;">

**이미지 설명**
- 상단 이미지는 검색 시에 나타나는 화면의 일부입니다.  

**동작**  

※ 모든 동작은 크롤링을 통해 수행되어야 합니다. 직접 키보드를 통해 입력하거나 클릭하는 과정은 없습니다.

- 1 드라이버에서 메타코드를 검색창에 입력합니다.  
- 2 검색 버튼을 클릭하세요.
    - 클릭 기능 사용 방법 추가로 첨부드립니다  
    : driver.find_element(By.CSS_SELECTOR, '요소 정보').click()

In [ ]:
# 코드를 작성해주세요

수집한 정보 중에서 상위 10개 데이터 출력 코드를 작성해주세요

In [ ]:
# 코드를 작성해주세요

,제목,작성자,좋아요,댓글수,작성일
0,[메타코드m],승우의 아카이브,5,5,2024.12.18
1,메타 프로그래밍: 코드가 코드를 생성하는 방식,info-ku 님의 블로그,1,0,2025.02.12
2,[정보처리기사] 메타코드 강의 후기 :: 1강 소프트웨어 설계,꾸준히,2,1,2024.12.02
3,[정보처리기사 필기] 메타코드M 강의 후기_(5강),우당탕탕 비전공자,0,0,2024.12.29
4,[메타 코드] 현직자 특강 및 데이터 분석 관련 강의를 듣고 싶다면?,Muns_day,3,0,2024.12.22
5,"메타코드 정보처리기사 필기 개념 강의, 수강 완료!",es25n.n 인문공학 기록,2,2,2024.12.22
6,[정처기] 정보처리기사 필기 강의 w 메타코드M,하파와 데이터,2,1,2024.12.09
7,"[정보처리기사] 메타코드M, 정보처리기사 필기 4주차(정보시스템 구축관리)",min8282,2,0,2024.12.22
8,[정보처리기사 필기 정리] 소프트웨어 설계 | 메타코드 강의 후기_1강,초보 개발자의 일기장,3,4,2024.12.01
9,"[Recommendation System] 메타코드M ""Kaggle 데이터를 활용한...",어떻게든 되겠지~,3,3,2024.12.04

---
## Q4. 자료형 변경 및 시각화를 수행해주세요

**출력 1과 출력 2**의 경우 크롤링 시행 시점에 따라,  
자료형 변경이 필요한 경우가 생길 수도 있고, 생기지 않을 수도 있습니다.  
자료형 변경이 필요하지 않은 경우에는, 진행하지 않으셔도 무관합니다.

**데이터 정보 확인 및 전처리를 수행해주세요**
- 현재 데이터프레임 자료형 확인해주세요
- 출력 결과와 동일하게 자료형 변형해주세요

**출력 1 : 자료형 변경 이전의 출력 결과를 출력해주세요**

In [ ]:
# 정답코드를 작성해주세요

**굵은 텍스트**<img src="./9th_Weeks_images/Q4_1.png">

**출력 2 : 자료형 변경 이후의 출력 결과를 출력해주세요**

In [ ]:
# 정답 코드를 작성해주세요

<img src="./9th_Weeks_images/Q4_2.png">

**출력 3 : 좋아요 상위 5개 글의 작성자, 글의 좋아요, 댓글수 확인를 확인해주세요**

In [ ]:
# 정답 코드를 작성해주세요

<img src="./9th_Weeks_images/Q4_3.png">

**출력 4: 출력 화면과 동일한 시각화 진행를 진행해주세요**
- 폰트 종류, 색상을 제외한 요소들은 시각화 결과에서 통일해주세요

In [ ]:
# 정답 코드를 작성해주세요

<img src="./9th_Weeks_images/Q4_4.png">

---
## Q5 페이지 자동 이동 및 글 정보 수집 기능

**url 주소 : 'https://www.tistory.com/'**

1) 웹 드라이버를 실행하고, 티스토리에 접속하세요
2) Python이 검색창에 입력되도록 코드를 작성해주세요
3) 검색 버튼이 클릭되도록 코드를 작성해주세요.
4) 반복문을 활용하여 5 페이지까지 자동으로 페이지 넘기는 코드를 작성해주세요
5) 자동 페이지 넘기기가 이루어지는 동안 게시글 정보를 수집하는 코드를 작성해주세요.
   - 수집정보 : 제목, 작성자, 좋아요, 댓글수, 작성일

- 위 과정은 모두 코드를 통해 자동으로 이루어져야 합니다.  

- url 주소 목록들을 활용하여 페이지 이동을 수행할 경우, 정답으로 인정되지 않습니다.

In [ ]:
''' 페이지 자동 넘기기 기능과 정보 수집 기능을 합친 코드를 작성해주세요 '''

''' 정답 코드를 작성해주세요 '''

<img src="./9th_Weeks_images/Q6_1.png">

In [ ]:
''' 전체 수집된 데이터 중에서 상위 데이터를 출력해주세요 '''

''' 아래 첨부된 이미지는 head 데이터의 예시 이미지입니다.'''

meta_info.head(5)

<img src="./9th_Weeks_images/Q6_2.png">

<img src="./9th_Weeks_images/Q6_Image_1.png">

In [ ]:
''' 전체 수집된 데이터 중에서 하위 데이터를 출력해주세요 '''

''' 아래 첨부된 이미지는 tail 데이터의 예시 이미지입니다.'''

meta_info.tail(5)

<img src="./9th_Weeks_images/Q6_3.png">

<img src="./9th_Weeks_images/Q6_Image_2.png">

## Q6. 데이터베이스 & 테이블 생성, 데이터 삽입  

※ 지시된 작업을 모두 수행하셔야 하며, 부분 점수는 없습니다.

In [ ]:
''' 데이터 확인용 코드 셀입니다. 참고용으로 확인해주세요 '''

tmp_df = pd.read_csv('./data_sql/Mall_Customers.csv')
display(tmp_df)

<img src="./9th_Weeks_images/Q7_1.png" alt="1;">

Mall_Customers 데이터 파일을 database에 넣은 뒤에 작업을 진행해주세요  

데이터베이스에 삽입할 데이터는 data_sql 폴더에 있습니다.  

csv와 sql 파일 형식을 모두 제공해드렸으니, 선호하시는 방법으로 database에 데이터를 넣으시면 됩니다.  

데이터베이스와 테이블의 구성 및 생성은 Python이 아닌 MySQL Workbench 환경에서 진행하셔도 됩니다.  
※ 정확하게 데이터베이스의 테이블을 구성하고 생성하는 것 또한 채점에 포함되는 요소입니다.  

문제를 통해 평가하고자 하는 내용은 아래와 같습니다.

**[수행 작업]**  
<작업 1> 테이블의 모든 데이터 추출

<작업 2> 조건에 맞게 데이터 가공 및 추출
- 동작 1 : 10세 이상 60대 미만 조건 고객만 선택합니다. 컬럼은 Age 컬럼을 활용합니다.
- 동작 2 : 해당 데이터에서 연령대별로 몇 명의 사람이 있는지 count를 수행합니다.  
※ 데이터에서 새로운 열을 생성하여 작업이 필요한지는 스스로 판단하시면 됩니다.  
※ 최종 결과물에서 집계 결과와 컬럼명이 동일하면 정답으로 인정됩니다.

In [ ]:
''' mysql 연동을 위한 코드를 작성해주세요/ '''

연결 성공

**<작업 1> 테이블의 모든 데이터 추출**

In [ ]:
'''
정답 쿼리를 작성하여 데이터를 데이터베이스로부터 추출하고

Pandas를 통해 출력해주세요
'''


query_all_data = """

"""

# 해당 코드를 통해 쿼리문의 실행 결과를 출력해주세요
# 데이터 추출, 전처리 등의 작업은 반드시 상단의 SQL 쿼리 작성 셀에서만 진행되어야 합니다.
cursor.execute(query_all_data)
result = cursor.fetchall()
columns = [desc[0] for desc in cursor.description]
query_df = pd.DataFrame(result, columns=columns)
query_df

<img src="./9th_Weeks_images/Q7_2.png" alt="1;">

**<작업 2> 조건에 맞게 데이터 가공 및 추출**
- 동작 1 : 10세 이상 60대 미만 조건 고객만 선택합니다. 컬럼은 Age 컬럼을 활용합니다.
- 동작 2 : 해당 데이터에서 연령대별로 몇 명의 사람이 있는지 count를 수행합니다.  
※ 데이터에서 새로운 열을 생성하여 작업이 필요한지는 스스로 판단하시면 됩니다.  
※ 최종 결과물에서 집계 결과와 컬럼명이 동일하면 정답으로 인정됩니다.

In [ ]:
'''
정답 쿼리를 작성하고 Pandas를 통해 출력해주세요
'''

query_agg = """

"""

# 해당 코드를 통해 쿼리문의 실행 결과를 출력해주세요
# 데이터 추출, 전처리 등의 작업은 반드시 상단의 SQL 쿼리 작성 셀에서만 진행되어야 합니다

cursor.execute(query_agg)
result = cursor.fetchall()
columns = [desc[0] for desc in cursor.description]
query_df = pd.DataFrame(result, columns=columns)
query_df

<img src="./9th_Weeks_images/Q7_3.png" alt="1;">

## Q7. Python_클래스를 작성해주세요

In [ ]:
''' 데이터 확인용 코드 셀입니다. 참고용으로 확인해주세요 '''
import pandas as pd
tmp_df = pd.read_csv('./data_sql/Mall_Customers.csv')
display(tmp_df)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

- Python 클래스를 작성해주세요

- 입력값, 출력값을 모두 신경써서 코드 작성을 해주세요

- 생성자 메서드
    - 데이터프레임과 성별을 나타내는 컬럼을 입력합니다.
    - 생성자 메서드 실행시 어떤 정보가 출력되는지 확인해주세요

- gender_visual 메서드
    - 입력된 컬럼들을 하나씩 순서대로 출력하는 기능을 수행합니다.
    - 차트의 색상은 통일시키지 않으셔도 되며, 나머지 요소는 동일하게 출력해주세요

- gender_info 메서드  
    - 데이터에서 성별 정보를 조회하는 메서드를 입니다.

    - 메서드 동작 1.
    성별을 나타내는 컬럼에 어떤 데이터가 있는지 출력합니다. (출력 예시) "성별 정보입니다. : ['Male' 'Female']""

    - 메서드 동작 2. 아래 동작을 수행하는 반복문을 작성합니다.
        - 조회하고자 하는 성별 정보를 입력하세요. 전체 정보를 원하시면 "전체"를 입력해주세요
        - [성별], [전체] 외의 정보를 입력시에 반복문은 종료됩니다.
        - (출력결과) 입력한 조건에 맞는 데이터에 대한 통계정보를 출력하세요
        - 해당 메서드의 출력 결과는 아래의 코드 셀을 확인해주세요.

In [ ]:
class visualize:
    def __init__(self, df, gender_col): # 기본 생성자 메서드입니다.
        ''' 정답코드를 작성해주세요 '''

    def gender_visual(self, numeric_cols): # Q8 문제에 해당하는 메서드입니다.
        ''' 정답코드를 작성해주세요 '''

    def gender_info(self): # Q9 문제에 해당하는 메서드입니다.
        ''' 정답코드를 작성해주세요 '''

- 상단에서 만든 클래스를 통해 아래와 같은 출력 결과를 만들어 주세요
- 생성자 메서드만 실행되었을 때의 결과입니다.

In [ ]:
visual_class = visualize(df=tmp_df,
                         gender_col = 'Gender')

<img src="./9th_Weeks_images/Q8_1.png" alt="1;">

gender_visual 메서드의 출력 결과를 나타내주세요.
  
차트의 색상, y축 범위는 통일시키지 않으셔도 되며,  
시각화 결과에서 나머지 요소는 동일하게 출력해주세요
- 배경, 제목, 범례, 가로선 등
- 검정색 세로 막대는 디폴트로 생성된 것으로 따로 설정은 하지 않으셔도 괜찮습니다.

In [ ]:
visual_class.gender_visual(numeric_cols = ['Age', 'Annual Income (k$)', 'Spending Score (1-100)'])

<img src="./9th_Weeks_images/Q8_2.png" alt="1">

<img src="./9th_Weeks_images/Q8_3.png" alt="1">

- gender_info 메서드의 출력 결과를 나타내주세요
- 반복문의 종료 조건도 정확하게 준수해주세요

In [ ]:
visual_class.gender_info()

<img src="./9th_Weeks_images/Q8_4.png" alt="1">

# Q8~Q10. Git 작업을 수행해주세요

---
- 첨부된 9주차_Git_문제.pdf 혹은 ppt 파일을 따라 Git 작업을 수행해주세요

※ 제출 방법
- GitHub 링크를 제출해주시면 됩니다.

## **🔎 [주관식 과제 수행 시 유의사항]**

> **✅ 1. 정확한 출력값과 요구사항 이행 필수**  

주관식 채점은 다음 기준에 따라 평가됩니다.

1)출력 결과의 정확성  
- 제공된 예시 결과와 동일한 출력이 나와야 합니다.  
- 단, 실시간 데이터나 인공지능 학습 등으로 출력값에 변동성이 존재할 수 있는 문제는 예외로 처리합니다.  

2)문제 요구사항의 충실한 반영  
- 조건, 컬럼명, 출력 형식 등 모든 요구사항을 빠짐없이 반영해야 합니다.  
- 사소한 조건도 놓치지 않도록 세심하게 코드를 작성해 주세요.  


> **✅ 2. 완성된 코드 제출 필수**

가. 제출한 코드 셀은 채점 시 직접 실행하여 결과를 확인할 수 있습니다.  

- 재실행 시에도 동일한 결과가 나와야 정답으로 인정됩니다.  

나. 버전 차이에 따른 미세한 수치 차이는 감안하나, 결과 형태나 구조가 다르면 감점 또는 오답 처리될 수 있습니다.  

다. 시각화 문제에서 색상 지정이 없다면, 기본(default) 색상 사용을 전제로 합니다.  
- 환경에 따라 색상이 다르게 출력되더라도 불이익은 없습니다.  

> **✅ 3. 사용자 선언 함수/클래스 문제 주의사항**

사용자 정의 함수, 클래스, 메서드와 관련된 문제에서는 추가적인 코드 없이도 함수만으로 정답 결과가 도출되어야 합니다.  
- ❌ 함수 외부에서 plt.title, print, info() 등을 추가하여 결과를 보완하면 오답 처리됩니다.  

> **✅ 4. 함수/클래스 선언 시 일관된 결과 유지**

가. 함수, 클래스, 메서드는 반복 실행 시에도 항상 동일한 결과를 반환해야 합니다.  
나. 채점 중 재실행 결과가 다르면 오답으로 처리됩니다.  

> **📌 [안내 정리]**  

가. 문제의 모든 조건을 꼼꼼히 확인하고 반영해 주세요.  
나. 과제는 실무와 유사한 기준으로 평가되며, 요구 조건을 충족하지 않을 경우 0점 처리될 수 있습니다.