In [1]:
import pandas as pd

In [11]:
tmp_df = pd.read_csv('./소방청_구조활동현황_20211231.csv', encoding='cp949')
tmp_seoul = tmp_df[tmp_df['발생장소_시']=="서울특별시"]
tmp_seoul

,번호,신고년월일,신고시각,출동년월일,출동시각,발생장소_시,발생장소_구,발생장소_동,사고원인,사고원인코드명_사고종별
0,1,2021-01-01,00:00,2021-01-01,00:10,서울특별시,구로구,구로동,화재,기타화재
1,2,2021-01-01,00:00,2021-01-01,00:10,서울특별시,구로구,구로동,화재,원인미상
2,3,2021-01-01,00:00,2021-01-01,00:04,서울특별시,구로구,구로동,화재,원인미상
3,4,2021-01-01,00:00,2021-01-01,00:10,서울특별시,구로구,구로동,화재,기타화재
4,5,2021-01-01,00:01,2021-01-01,00:04,서울특별시,중랑구,묵동,잠금장치개방,신변확인
...,...,...,...,...,...,...,...,...,...,...
796851,796852,2021-12-31,23:46,2021-12-31,23:46,서울특별시,금천구,독산동,화재,기타화재
796852,796853,2021-12-31,23:46,2021-12-31,23:46,서울특별시,금천구,독산동,안전조치,소방시설 오작동
796853,796854,2021-12-31,23:46,2021-12-31,23:46,서울특별시,금천구,독산동,화재,기타화재
796854,796855,2021-12-31,23:46,2021-12-31,23:46,서울특별시,양천구,신정동,안전조치,기타 안전조치
796867,796868,2021-12-31,23:59,2021-12-31,23:59,서울특별시,강동구,천호동,기타,기타

In [14]:
tmp_seoul['발생장소_구'].value_counts().to_frame().reset_index()

   발생장소_구  count
0     강남구  11922
1    영등포구   9952
2     송파구   9044
3     강서구   8888
4     마포구   7669
5     서초구   7277
6     관악구   7204
7     은평구   6731
8     노원구   6546
9     강동구   6167
10    중랑구   6100
11    구로구   5610
12    성북구   5610
13    강북구   5538
14    광진구   5410
15    용산구   5404
16   동대문구   5366
17    종로구   5188
18    도봉구   5011
19   서대문구   4948
20    양천구   4894
21    동작구   4823
22     중구   4333
23    금천구   4285
24    성동구   3978
25  서울특별시      9